import { NextResponse } from 'next/server';
import { GoogleGenerativeAI, FunctionDeclaration, SchemaType, FunctionCallingMode } from '@google/generative-ai';
import { AI_MODELS } from '@/lib/ai/models';
import { executeWithRetry } from '@/lib/ai/retry';

export async function POST(req: Request) {
  try {
    const apiKey = process.env.GEMINIAPIKEY || process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      return NextResponse.json({ error: 'Missing Gemini API Key' }, { status: 400 });
    }
    const genAI = new GoogleGenerativeAI(apiKey);

    const { resumeData, prompt: userPrompt } = await req.json();

    if (!resumeData || !userPrompt) {
      return NextResponse.json({ error: 'Missing resume data or prompt' }, { status: 400 });
    }

    const editResumeDataDeclaration: FunctionDeclaration = {
      name: 'editResumeData',
      description: 'Applies JSON patches to the resume data based on user requests.',
      parameters: {
        type: SchemaType.OBJECT,
        properties: {
          patches: {
            type: SchemaType.ARRAY,
            description: 'A list of updates to apply to the resume JSON.',
            items: {
              type: SchemaType.OBJECT,
              properties: {
                path: {
                  type: SchemaType.STRING,
                  description: 'The JSON path to update, e.g., "personalInfo.summary" or "skills.0.items"',
                },
                value: {
                  type: SchemaType.STRING,
                  description: 'The new value to set at the specified path (as a string, even if it represents an array or object, which will be parsed).',
                }
              },
              required: ['path', 'value'],
            },
          }
        },
        required: ['patches'],
      },
    };

    const systemInstruction = `
You are an expert ATS resume editor and FAANG-grade AI assistant. The user wants to make a targeted edit to their existing resume.

CURRENT RESUME JSON:
${JSON.stringify(resumeData, null, 2)}

INSTRUCTIONS:
1. Understand the user's request and locate the relevant sections in the provided JSON.
2. Formulate the precise edits required.
3. You MUST call the editResumeData function to apply these edits.
4. Provide the exact path and the new value. If adding an item to an array, rewrite the entire array and pass its stringified version.
5. Strictly forbid AI filler words, corporate jargon, and robotic structures. Use direct, factual, and highly humanized engineering tone.
`;

    const finalResult = await executeWithRetry(async (modelName) => {
      const model = genAI.getGenerativeModel({
        model: modelName,
        tools: [
          {
            functionDeclarations: [editResumeDataDeclaration],
          },
        ],
        toolConfig: {
          functionCallingConfig: { mode: FunctionCallingMode.ANY },
        },
        systemInstruction: {
          role: "system",
          parts: [{ text: systemInstruction }]
        },
      });

      const chat = model.startChat();
      const result = await chat.sendMessage(userPrompt);
      const response = result.response;
      const calls = response.functionCalls();

      if (calls && calls.length > 0) {
        const call = calls[0];
        if (call.name === 'editResumeData') {
          return (call.args as any).patches;
        }
      }

      // Fallback if no function was called
      let aiText = '';
      try {
        aiText = response.text();
      } catch (e) { }
      throw new Error('No edit was generated by the AI.' + (aiText ? ` AI said: ${aiText}` : ''));
    }, AI_MODELS.CHAT);

    return NextResponse.json({ patches: finalResult });

  } catch (error) {
    console.error('AI Chat Edit Error:', error);
    return NextResponse.json(
      { error: `Chat Edit Error: ${error instanceof Error ? error.message : String(error)}` }, 
      { status: 500 }
    );
  }
}
