import { NextResponse } from 'next/server';
import { GoogleGenerativeAI, FunctionDeclaration, SchemaType } from '@google/generative-ai';

const apiKey = process.env.GEMINIAPIKEY || process.env.GEMINI_API_KEY || '';
const genAI = new GoogleGenerativeAI(apiKey);

export async function POST(req: Request) {
  try {
    const { resumeData, prompt: userPrompt } = await req.json();

    if (!resumeData || !userPrompt) {
      return NextResponse.json({ error: 'Missing resume data or prompt' }, { status: 400 });
    }

    const editResumeDataDeclaration: FunctionDeclaration = {
      name: 'editResumeData',
      description: 'Applies JSON patches to the resume data based on user requests.',
      parameters: {
        type: SchemaType.OBJECT,
        properties: {
          patches: {
            type: SchemaType.ARRAY,
            description: 'A list of updates to apply to the resume JSON.',
            items: {
              type: SchemaType.OBJECT,
              properties: {
                path: {
                  type: SchemaType.STRING,
                  description: 'The JSON path to update, e.g., "personalInfo.summary" or "skills.0.items"',
                },
                value: {
                  type: SchemaType.STRING,
                  description: 'The new value to set at the specified path (as a string, even if it represents an array or object, which will be parsed).',
                }
              },
              required: ['path', 'value'],
            },
          }
        },
        required: ['patches'],
      },
    };

    const systemInstruction = `
You are an expert ATS resume editor and FAANG-grade AI assistant. The user wants to make a targeted edit to their existing resume.

CURRENT RESUME JSON:
${JSON.stringify(resumeData, null, 2)}

INSTRUCTIONS:
1. Understand the user's request and locate the relevant sections in the provided JSON.
2. Formulate the precise edits required.
3. You MUST call the editResumeData function to apply these edits.
4. Provide the exact path and the new value. If adding an item to an array, rewrite the entire array and pass its stringified version.
5. Strictly forbid AI filler words, corporate jargon, and robotic structures. Use direct, factual, and highly humanized engineering tone.
`;

    const model = genAI.getGenerativeModel({
      model: 'gemini-1.5-pro-latest',
      tools: [
        {
          functionDeclarations: [editResumeDataDeclaration],
        },
      ],
      systemInstruction: {
        role: "system",
        parts: [{ text: systemInstruction }]
      },
    });

    const chat = model.startChat();

    const result = await chat.sendMessage(userPrompt);
    const response = result.response;
    const calls = response.functionCalls();

    if (calls && calls.length > 0) {
      const call = calls[0];
      if (call.name === 'editResumeData') {
        const patches = (call.args as any).patches;
        // Process patches on the server or return them to the frontend
        // The prompt asked for: "the frontend chatbot component uses the Zustand store's set() functions to instantly apply the humanized text to the live document."
        return NextResponse.json({ patches });
      }
    }

    // Fallback if no function was called
    return NextResponse.json({ error: 'No edit was generated by the AI.' }, { status: 400 });

  } catch (error) {
    console.error('AI Chat Edit Error:', error);
    return NextResponse.json(
      { error: `Chat Edit Error: ${error instanceof Error ? error.message : String(error)}` }, 
      { status: 500 }
    );
  }
}
